blog/urls.py
from django.conf.urls import url
from blog import views
app_name = "blog"

urlpatterns = [
    url(r'^formpage/', views.form_name_view, name='form_name'),
    url(r'^signup/', views.authentication_view, name='authentication_name'),
    url(r'^main_page/', views.main_page, name='main_page'),
    url(r'^logout/', views.user_logout, name='user_logout'),
    
    
    url(r'^user_login/', views.user_login, name='user_login'),
   
   
]

mysite/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path



urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^polls/', include("blog.urls" , namespace="polls")),#manageNitkroute
    url(r'^pastebin/', include("pastebin.urls" , namespace="pastebin")),#pastebin
    url(r'^tinymce/', include('tinymce.urls')),#pastebin
    url(r'^codefundo/', include("codefundo.urls" , namespace="codefundo")),#codefundo
    


]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User



class input(models.Model):
    event_description = models.TextField(blank=False,null=False) 
    venue =             models.CharField(max_length=50)
    time =              models.TimeField(unique=False)
    date=               models.DateField(blank=True, null=True)
    def __str__(self):
        return  self.event_description

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=True)
    picture = models.ImageField(upload_to="profile_pics",blank=True)

    def __str__(self):
        return self.user.username

blog/forms.py
from django import forms
from django.core import validators
from blog.models import input,UserProfileInfo,User




class FormName(forms.Form):
    name=forms.CharField()
    email=forms.EmailField()
    text=forms.CharField()
    botcatcher=forms.CharField(required=False,widget=forms.HiddenInput,)


class AuthorForm(forms.ModelForm):
 
    class Meta:
        model = input
        fields = "__all__"
        error_messages = {
            "time":{
                "unique":"hi there! it looks like there is some event on the same time ",
            }
        }

class Authentic(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields =("username","password","first_name","last_name","email",)

class UserProfile(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ("picture",)

blog/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
import datetime
from django import template

from django.shortcuts import render,get_object_or_404
from blog.forms import AuthorForm,Authentic,UserProfile
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from blog.models import input
from datetime import datetime
     
...
        
def main_page(request):
    qs = input.objects.all()
    qs = sorted(qs,key=lambda x:x.date,reverse=False)
    if request.method=="POST":
         mydate=request.POST.get("date",)
         qs = input.objects.filter(date=mydate)
         qs = sorted(qs,key=lambda x:x.time,reverse=False)
         return render(request,"blog/index_page.html",{"qs":qs,"mydate":mydate})

        


    else:
          return render(request,"blog/index_page.html",{"qs":qs,})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("main_page"))

@login_required
def form_name_view(request):
    form=AuthorForm()
    if request.method=="POST":
        form=AuthorForm(request.POST)

        if form.is_valid():
            form.save()
            return render(request,"blog/ss.html",{"form":form }) 
            
        else:
            print("error")    
    return render(request,"blog/form_page.html",{"form":form })        

def authentication_view(request):
    registered = False
    
    if request.method=="POST":
     auth=Authentic(request.POST )

     if auth.is_valid():
         auth=auth.save(commit=False)
         auth.set_password(auth.password)   
         #hashing the password
         auth.save()
         registered=True


     else :
         print("error")
    else:
        auth=Authentic()     
    return render(request,"blog/signup.html",{"auth":auth,"registered":registered })        


def user_login(request):
    if request.method=="POST":
        username=request.POST.get("username")
        password=request.POST.get("password")

        user=authenticate(username=username,password=password)


        if user:
            login(request,user)
            return HttpResponseRedirect(reverse("blog:form_name",))
        else:
            return HttpResponse("Invalid Username and Password")
    else :
        return render(request,"blog/login.html",{})

blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Calender WebApp</title>
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static "blog/letcode.css" %}">
    <!--  jQuery -->
<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>

<!-- Isolated Version of Bootstrap, not needed if your site already uses Bootstrap -->
<link rel="stylesheet" href="https://formden.com/static/cdn/bootstrap-iso.css" />

<!-- Bootstrap Date-Picker Plugin -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>


<style>
    .parallax1 {
    /* The image used */
   
    background-image: url("{% static "blog/nitk.png" %}");

    /* Set a specific height */
    height: 30em; 

    /* Create the parallax scrolling effect */
    background-attachment: fixed;
    background-position: center;
    background-repeat: no-repeat;
    background-size:150em ;
    width: 100%;
}

.signup{
    margin-left: 25em;
    
   
}
.image{
    background-image: url("{% static "blog/nitk.png" %}");
    background-repeat:repeat-y;
    width:100%;
    margin:0; 
    padding:0; 
    height:100%;
    
}

</style>
</head>
<body>
       
           
    
       
            {% block main_content %}
    {% endblock %}


</div>
</body>
</html>

blog/templates/blog/form_page.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Event Entry</title>
        <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style> 
        </style>
    </head>
    <body>
<div class="container">
<div class="row">
  <div class="col-sm-8">
          <h1 style="font-family: cursive">Please put the details of your Event here!</h1><br>
            <form class="form-horizontal" action="/polls/formpage/" method="POST">
                
                {% csrf_token %}
       {{ form.non_field_errors }}
        <div class="container" style="font-family: cursive">
            What's the event:<br>{{form.event_description }}<br><br>
             Time:<br>{{form.time}}<em>&nbsp;Enter the time in the format HH:MM:SS</em><br><br>
        Date:<br>{{ form.date }}<em>&nbsp;Enter the date in the format YYYY-MM-DD</em><br><br>
       Venue:<br>{{ form.venue }}<br><br></div>
                <input class="btn btn-primary" type="submit" value="Submit">   
            </form>   
  </div>
     <div class="col-sm-4">
<img style="margin-top: 10em;" src="{% static "blog/ev3.jpg" %}">
     </div>
  </div>
</div>



    </body>
</html>

blog/templates/blog/index_page.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Forms</title>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        </head>
        
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="mystyle.css">
        <link rel="stylesheet" type="text/css" href="content.css">

         <!--  jQuery -->
<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>

<!-- Isolated Version of Bootstrap, not needed if your site already uses Bootstrap -->
<link rel="stylesheet" href="https://formden.com/static/cdn/bootstrap-iso.css" />

<!-- Bootstrap Date-Picker Plugin -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" >
      <style>  
.parallax1 {
    /* The image used */
   
    background-image: url("{% static "blog/Events.jpg" %}");

    /* Set a specific height */
    height: 30em; 

    /* Create the parallax scrolling effect */
    background-attachment: fixed;
    background-position: center;
    background-repeat: no-repeat;
    background-size:150em;
    width: 100%;
}
.footer{
    background-color:lightgrey;
    height:3em;
    font-size: 2em;
    font-family: cursive;
    text-align: center;
    
}
</style>
    </head>
    <body>
<div class="row">
    <div class="col-sm-4">
            <img src="{% static "blog/Events.jpg" %}"  width="500em" height="500em" alt="Girl in a jacket">
           <!--login system-->
        <div class="container">
                <h1 style="font-family: cursive;">  Login Here! </h1><br>
                <div style="margin-right: 40em;">
                <form class="form-horizontal" action="{% url "blog:user_login" %}" method="POST">
                    {% csrf_token %}
                    
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="username">Username:</label>
                        <div class="col-sm-10">
                     <input type="text" class="form-control" name="username" placeholder="Enter username" >
                        </div>
                    </div>
                  
                    <div class="form-group">
                       <label class="control-label col-sm-2"  for="password">Password:</label>
                     <div class="col-sm-10">
                       <input class="form-control" type="password" name="password" placeholder="Enter Password">
                   </div>
                    </div>
                    <div class="form-group">        
                        <div class="col-sm-offset-2 col-sm-10">
                                <div class="checkbox">
                                        <label><input type="checkbox" name="remember"> Remember me</label>
                                    </div>
                                  </div>
                                </div>
                     <div class="form-group">       
                        <div class="col-sm-offset-2 col-sm-10">
                     <input type="submit" name=""   class="btn btn-default" value="Login">
                        </div>
                     </div>
                    
                    </form>
                      </div>
                    </div>
                        </div>
     
  
            <div class="col-sm-8" >
                       <!--logo-->
                       <div class="row">
                            <div class="col-sm-4">
                       <img style="margin-left: 3em" src="{% static "blog/nitk_logo.png" %}"> 
                            </div>
                            <div class="col-sm-8">
                        <div style="font-family: cursive ; font-size: 2em ;" class="container">National Institute Of Technology<br> Karnataka,Surathkal<br><br>
                            राष्ट्रीय प्रौद्योगिकी संस्थान कर्नाटक,सुरथकल</div>
                            </div>
                       </div>


            <nav class="navbar navbar-default" >
                    <div class="container">
                    <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>                        
                                  </button>
                        <a href="/polls/main_page/" onclick="callaboutme()"class="navbar-brand">EVENTS @ NITK</a>  
                    </div>
                    <div class="collapse navbar-collapse" id="myNavbar">
                        <ul class="nav navbar-nav">
                     <li>  <a href="/polls/signup/" >SIGNUP</a>    </li>
                   
                     </ul> 
                    </div>
            </nav>
           
            <script>
        webshim.setOptions('forms-ext', {
    replaceUI: 'auto',
    types: 'date',
    date: {
        startView: 2,
        inlinePicker: true,
        classes: 'hide-inputbtns'
    }
});
webshim.setOptions('forms', {
    lazyCustomMessages: true
});
//start polyfilling
webshim.polyfill('forms forms-ext');

//only last example using format display
$(function () {
    $('.format-date').each(function () {
        var $display = $('.date-display', this);
        $(this).on('change', function (e) {
            //webshim.format will automatically format date to according to webshim.activeLang or the browsers locale
            var localizedDate = webshim.format.date($.prop(e.target, 'value'));
            $display.html(localizedDate);
        });
    });
});
</script>
<body>
                <div class="container-fluid" >
                        <form action="/polls/main_page/" class="ws-validate" method="POST">{% csrf_token %}
                           
                               <div class="form-row">
                                   <input type="date" class="hide-replaced" name="date" />
                               </div>
                               <br>
                               <div class="form-row">
                                   <input class="btn btn-primary" type="submit" />
                               </div>
                           </form>
          <br>
                        {% if qs %}
                        {% for items in qs %}
                           <div class="container" style="font-family: cursive">
                            <div class="col-md-8" style="background-color: lightgrey;
                            border: 1px solid #000000;
                            border-radius: 1%;">
                                DATE: {{items.date}}<br>
                               TIME:{{items.time}}<br>
                               EVENT:   {{items.event_description}}<br>
                               VENUE:    {{items.venue}}<br>
                               </div>
                               <br>
                               <br>
                    </div>
                    <br>
                        
                    {% endfor %}

                    {% else %}
                        <div style="font-family: cursive">There's no Event scheduled for the day, enjoy in your room.</div>
                        {% endif %}
                        <br>

         
       
   </div>
</div>
</div>
<div class="footer" style="height: 50px;"><div style="margin-top: 15px;">&copy;Manan Poddar</div></div> 

    </body>
</html>

blog/templates/blog/login.html
{% extends "blog/base.html" %}
{% block main_content %}

                
      
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

      <div class="container">
<h1 style="font-family: cursive; margin-left: 10em;">  Login Here! </h1><br>
<form class="form-horizontal" action="{% url "blog:user_login" %}" method="POST">
    {% csrf_token %}
    
    <div class="form-group">
        <label class="control-label col-sm-2" for="username">Username:</label>
        <div class="col-sm-10">
     <input type="text" class="form-control" name="username" placeholder="Enter Username" >
        </div>
    </div>
  
    <div class="form-group">
       <label class="control-label col-sm-2"  for="password">Password:</label>
     <div class="col-sm-10">
       <input class="form-control" type="password" name="password" placeholder="Enter Password">
   </div>
    </div>
    <div class="form-group">        
        <div class="col-sm-offset-2 col-sm-10">
                <div class="checkbox">
                        <label><input type="checkbox" name="remember"> Remember me</label>
                    </div>
                  </div>
                </div>
     <div class="form-group">       
        <div class="col-sm-offset-2 col-sm-10">
     <input type="submit" name=""   class="btn btn-default" value="Login">
        </div>
     </div>
    
    </form>
      </div>
        </div>
        {% endblock %}
      

blog/templates/blog/signup.html
{% extends "blog/base.html" %}
{% block main_content %}

<!--
{% if registered %}
<h1> thankyou for registering</h1>
<a href="http://127.0.0.1:8000/polls/user_login/" >LOGIN</a>    

{% else %}
<div class="container-fluid image">

 <form method="POST" action="/polls/signup/" enctype="multipart/form-data">{% csrf_token %}
    {{ auth.non_field_errors }}
   <div class="signup" >
        <h1 style="font-size: 4em;">register here :</h1><br>
  
<div style="font-size: 1.5em ; color: white">
        <div class="row">
       <div class="col-lg-3">
        <label  for="username">username :</label></div>
        <div class="col-lg-3" >{{auth.username}}</div>
    </div>
   
</br></br>


    
<div class="row">
        <div class="col-lg-3">
         <label  for="password">password :</label></div>
         <div class="col-lg-3" >{{auth.password}}</div>
     </div>
    
 </br></br>

 <div class="row">
        <div class="col-lg-3">
         <label  for="username">First Name :</label></div>
         <div class="col-lg-3" >{{auth.first_name}}</div>
     </div>
    
 </br></br>

 <div class="row">
        <div class="col-lg-3">
         <label  for="username">Last Name :</label></div>
         <div class="col-lg-3" >{{auth.last_name}}</div>
     </div>
    
 </br></br>
    
 <div class="row">
        <div class="col-lg-3">
         <label  for="username">Email Id :</label></div>
         <div class="col-lg-3" >{{auth.email}}</div>
     </div>
    
 </br></br>

</div>
   

</br>

</br>

    <div class="form-group">       
        
     <input type="submit" name="register"   class="btn btn-primary" style="margin-left: 22em" value="REGISTER">
        
     </div>

    </div>

    
    </form>

{% endif %}-->
{% load widget_tweaks %}

{% if registered %}

<div class="container">
    <div style="text-align: center">
       <h1 style="margin-top: 4em;"> SUCCESSFULLY REGISTERED!<h1>
    <a href="/polls/user_login/" type="button" class="btn btn-primary"> Go to Login Page!</a>
</div>

{% else %}
<div class="container">
    <h1>Sign Up! </h1><BR>
<form method="POST" nonvalidate action="/polls/signup/" enctype="multipart/form-data">{% csrf_token %}
  {% csrf_token %}

  {% for hidden_field in auth.hidden_fields %}
    {{ hidden_field }}
  {% endfor %}

  {% if auth.non_field_errors %}
    <div class="alert alert-danger" role="alert">
      {% for error in auth.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>
  {% endif %}

  {% for field in auth.visible_fields %}
    <div class="form-group">
      {{ field.label_tag }}

      {% if auth.is_bound %}
        {% if field.errors %}
          {% render_field field class="form-control is-invalid" %}
          {% for error in field.errors %}
            <div class="invalid-feedback">
              {{ error }}
            </div>
          {% endfor %}
        {% else %}
          {% render_field field class="form-control is-valid" %}
        {% endif %}
      {% else %}
        {% render_field field class="form-control" %}
      {% endif %}

      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    </div>
  {% endfor %}

  <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>

{% endif %}

{% endblock %}

blog/templates/blog/ss.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<div class="container">
    <div style="text-align: center">
       <h1 style="margin-top: 4em;"> SUCCESSFULLY SUBMITTED!<h1>
    <a href="/polls/main_page/" type="button" class="btn btn-primary"  > Go to Main Page!</a>
</div>

</div>

blog/templates/blog/user.html
{% extends "blog/base.html" %}
{% block main_content %}

<div class="container">
{% if registered %}
<h1> Thankyou for Registering</h1>
{% else %}
 <h1>Register Here:</h1>

 <form method="POST" action="/polls/users/" enctype="multipart/form-data">
{{auth.as_p}}
{% csrf_token %}



<input type ="submit" name="submit" value="Register" >
</form>
</div>
{% endif %}



{% endblock %}