blog/urls.py
from django.conf.urls import url
from blog import views
app_name = "blog"

urlpatterns = [
    url(r'^formpage/', views.form_name_view, name='form_name'),
    url(r'^signup/', views.authentication_view, name='authentication_name'),
    url(r'^main_page/', views.main_page, name='main_page'),
    url(r'^logout/', views.user_logout, name='user_logout'),
    
    
    url(r'^user_login/', views.user_login, name='user_login'),
   
   
]

codefundo/urls.py
from django.conf.urls import url
from codefundo import views
app_name = "codefundo"

urlpatterns = [
    #url(r'^$', views.front_page, name='front_page'),

    url(r'^main_page/', views.main_page, name='main_page'),
    url(r'^user_logout/', views.user_logout, name='user_logout'),
    url(r'^main_log_page/', views.main_log_page, name='main_log_page'),

    url(r'^admin_login/', views.admin_login, name='admin_login'),
    
    url(r'^user_login/', views.user_login, name='user_login'),
    url(r'^user_signup/', views.user_signup, name='user_signup'),
    url(r'^registered',views.registered, name='registered'),
    url(r'^aboutus',views.aboutus, name='aboutus'),
    url(r'^alreadyreg',views.alreadyreg, name='alreadyreg'),
    url(r'^afterlogsign',views.afterlogsign, name='afterlogsign'),
    url(r'^thanku',views.thanku,name='thanku')

  






   
   
   
]

mysite/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path



urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^polls/', include("blog.urls" , namespace="polls")),#manageNitkroute
    url(r'^pastebin/', include("pastebin.urls" , namespace="pastebin")),#pastebin
    url(r'^tinymce/', include('tinymce.urls')),#pastebin
    url(r'^codefundo/', include("codefundo.urls" , namespace="codefundo")),#codefundo
    


]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

codefundo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator,MaxLengthValidator
class user_details(models.Model):
    aadhar_no =models.IntegerField(default=0, unique=True)
    pincode   =models.IntegerField(default = 0)
    city  = models.CharField(max_length=20,default=None)

class track_users(models.Model):
    pincode = models.IntegerField( default=0,unique=True)
    user_count=models.IntegerField(default=0)
    city  = models.CharField(max_length=20,default=None)
    fund = models.IntegerField(default=0)

class gov_fund(models.Model):
    fund = models.IntegerField(default=0)

codefundo/forms.py
from django.db import models
from django import forms
from codefundo.models import user_details,User,gov_fund

class input(forms.ModelForm):
    class Meta:
        model = user_details
        fields= '__all__'

class Authentic(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields =("username","password","first_name","last_name","email",)


class fund_gov(forms.ModelForm):
    class Meta:
        model = gov_fund
        fields= '__all__'

codefundo/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
import datetime
from django import template
from django.utils import timezone


from django.shortcuts import render,get_object_or_404
from codefundo.forms import input,Authentic,fund_gov
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from codefundo.models import user_details,gov_fund,track_users
from datetime import datetime,date,timedelta
from django.views.generic.edit import CreateView, UpdateView, DeleteView
form=input()
def main_page(request):
    form=input()
    total_fund = gov_fund.objects.all()
    s=0
    for i in total_fund:
        s=s+i.fund
    
    #mypaste=user_details.objects.all()
    #mypaste = sorted(mypaste,key=lambda x:x.url,reverse=True)
    t=0
    t_obj=0
    count_user=track_users.objects.all()
    for i in count_user:
        t = t + i.user_count
        t_obj = t_obj + 1
    print(t)
    per_person_fund = s/t
    if request.method=="POST":
        form=input(request.POST)
         # myd
        current=form.save(commit=False)
        try:
            content_object=track_users.objects.get(pincode = current.pincode)
        except:
            content_object = None
        if content_object == None:
            content_object = track_users()
            content_object.pincode=current.pincode
            content_object.city=current.city
             
            content_object.user_count=1
            content_object.fund = per_person_fund * content_object.user_count
            content_object.save()
        else :
            content_object.user_count=content_object.user_count+1
            content_object.fund = per_person_fund * content_object.user_count

            content_object.save()
         
          
         
            
        if form.is_valid():
            
         form.save()
         count_user=track_users.objects.all()
         return render(request,"codefundo/registered.html",{"form":form,"objects":count_user,}) 
        else:
         return render(request,"codefundo/alreadyreg.html")   
    count_user=track_users.objects.all()

    return render(request,"codefundo/home.html",{"form":form,"objects":count_user,} )
@login_required
def main_log_page(request):
    form=fund_gov()
    #mypaste=user_details.objects.all()
    #mypaste = sorted(mypaste,key=lambda x:x.url,reverse=True)
    sumq=0
    if request.method=="POST":
          form=fund_gov(request.POST)
         # mydate=request.POST.get("date",)
          if form.is_valid():
           # cur_obj = form.save(commit=False)
            form.save()
            item= gov_fund.objects.all()
            for i in item:
                 sumq=sumq+(int)(i.fund)
        
            form.save()
            return render(request,"codefundo/main_loggedin_page.html",{"sum":sumq}) 
          else:
               return render(request,"codefundo/return_valid_data.html")   
    return render(request,"codefundo/main_loggedin_page.html",{"form":form } )



def user_signup(request):
    registered = False
    form=input()
    if request.method=="POST":
     auth=Authentic(request.POST )

     if auth.is_valid():
         auth=auth.save(commit=False)
         auth.set_password(auth.password)   
         #hashing the password
         auth.save()
         registered=True
         return HttpResponseRedirect(reverse("codefundo:user_login"))

     else :
         print("error")
    else:
        auth=Authentic()     
    return render(request,"codefundo/signup.html",{"auth":auth,"registered":registered,"form":form })        

       


def user_login(request):
    if request.method=="POST":
        username=request.POST.get("username")
        password=request.POST.get("password")

        user=authenticate(username=username,password=password)


        if user:
            login(request,user)
            return HttpResponseRedirect(reverse("codefundo:afterlogsign"))
        else:
            return render(request,"codefundo/return_invalid_user.html")
    else :
        return render(request,"codefundo/login.html",{"form":form},)

def admin_login(request):
   
        return HttpResponseRedirect("./admin")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("codefundo:main_page",))

def registered(request):
    return render(request,"codefundo/registered.html",{"form":form})

def aboutus(request):
    return render(request,"codefundo/aboutus.html",{"form":form})

def alreadyreg(request):
    return render(request,"codefundo/alreadyreg.html",{"form":form})

def afterlogsign(request):
    print("asdf")
    form=fund_gov()
    #mypaste=user_details.objects.all()
    #mypaste = sorted(mypaste,key=lambda x:x.url,reverse=True)
    sumq=0
    if request.method=="POST":
          form=fund_gov(request.POST)
          print("asdfasdf")
         # mydate=request.POST.get("date",)
          if form.is_valid():
           # cur_obj = form.save(commit=False)
            form.save()
            item= gov_fund.objects.all()
            for i in item:
                 sumq=sumq+(int)(i.fund)
            
            form.save()
            print("manan")
            return render(request,"codefundo/thanku.html") 
          
          else:
               return render(request,"codefundo/return_valid_data.html")   
    return render(request,"codefundo/afterlogsign.html",{"form":form } )

def thanku(request):
    return render(request,"codefundo/thanku.html")
    

codefundo/templates/codefundo/aboutus.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Microsoft Codefundoo</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
  <style>
    /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
    .row.content {height: 1500px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      background-color: #dbdbf0;
     height: 100%
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height: auto;} 
    }
  </style>
</head>


<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <h4>MICROSOFT</h4>
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="/codefundo/main_page/">Home</a></li>
        <li><a href="/codefundo/aboutus/">About Us</a></li>
        <li><a href="/codefundo/user_signup/">Sign Up</a></li>
        <li><a href="/codefundo/user_login">Log In</a></li>
      </ul><br>

      <div class="container">
        <form  action="/codefundo/main_page/" method="POST">
      
            {% csrf_token %}
   {{ form.non_field_errors }}

        
       <label for="Aadhar">Aadhar Card:</label>
         <br> {{form.aadhar_no}}<br><br>
       
  
         <label for="pin">Postal Code</label>
        <br> {{form.pincode}}
        <br><br>

        <label for="City">City</label>
        <br>  {{form.city}}
        <br>

<br>
<br>
            <input class="btn btn-primary" type="submit" value="Submit Response">   
        </form>  
<br>
<br> 

</div>
   
    </div>

    <div class="col-sm-9">
		<body style="background-image:url({% static 'codefundo/water1.jpg' %}); background-repeat: no-repeat">
      <br><br><br><br><br>

      

      

      <h1 style="text-align: center"><strong style="color:aliceblue">About Creators</strong></h1>
<br><br><br>
      <div class="container">
      <div class="row">
		  <div class="animated fadeInLeft">
        <div class="col-sm-2 text-center">
          <img src='{% static "codefundo/manan.png" %}' class="img-circle" height="200" width="200" alt="Manan">
        </div>
        <div class="col-sm-10">
          <h4><strong>Manan Poddar</strong></h4>
          <p>Sophomore student of National Institute Of Technology,Karnataka </p>

          <br>
          <a class ="btn btn-primary" href="https://mananpoddar.github.io">personal website</a>
		</div>
		</div>
	</div>
		<br>
		<br>
		<div class="row">
		<div class="animated slideInLeft delay-1s">
        <div class="col-sm-2 text-center">
          <img src='{% static "codefundo/shashank.jpg" %}' class="img-circle" height="200" width="200" alt="Shashank">
        </div>
        <div class="col-sm-10">
          <h4><strong>Shashank Jaiswal</strong> </h4>
          <p>Sophomore student of National Institute Of Technology,Karnataka </p>
		 </div>
		</div> 
	</div>
		  <br>
		  <br>
	
			
          </div>
        </div>
	  </div>
	</body>
    </div>
  </div>
</div>

<footer class="container-fluid">
  <p>Contact Us</p>
  <p>mananpoddarm@gmail.com</p>
  <p>17shashank17@gmail.com</p>
  <p>vmehra25@yahoo.com</p>
</footer>


</html>

codefundo/templates/codefundo/admin_login.html
{% block main_content %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Microsoft Codefundoo</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
    /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
    .row.content {height: 1500px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      background-color: #f1f1f1;
      height: 100%;
    }
    .loginBox
{
	position: absolute;
	top: 50%;
	left: 50%;
	transform: translate(-50%,-50%);
	width: 400px;
	height: 500px;
	padding: 80px 40px;
	box-sizing: border-box;
	background: rgba(0,0,0,.5);
}
    
    .circle
  {
    border-radius: 50%;
    width: 200px;
    height: 200px; 
    background-color: rgb(45, 218, 45)
  }
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height: auto;} 
    }
  </style>
</head>

<body style="background-image:url({% static 'codefundo/water1.jpg' %}); background-repeat: no-repeat">
<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <h4>MICROSOFT</h4>
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="/codefundo/main_page/">Home</a></li>
        <li><a href="/codefundo/aboutus/">About Us</a></li>
        <li><a href="/codefundo/user_signup/">Sign Up</a></li>
        <li><a href="/codefundo/user_login">Log In</a></li>
      </ul><br>

      <div class="container">
        <form  action="/codefundo/main_page/" method="POST">
      
            {% csrf_token %}
   {{ form.non_field_errors }}

        
       <label for="Aadhar">Aadhar Card:</label>
         <br> {{form.aadhar_no}}<br><br>
       
  
         <label for="pin">Postal Code</label>
        <br> {{form.pincode}}
        <br><br>

        <label for="City">City</label>
        <br>  {{form.city}}
        <br>

<br>
<br>
            <input class="btn btn-primary" type="submit" value="Submit Response">   
        </form>  
<br>
<br> 

</div>

</div>

<div class="col-sm-9">


      <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
      <br><br><br><br><br><br><br><br><br><br><br><br><br><br>
     
      <div class="container">
          <div style="center">
        <div class="loginBox">
<h1 style=" text-align: center"><strong style="color:aliceblue">Login Here!</strong> </h1><br>
<form class="form-horizontal" action="{% url "codefundo:admin_login" %}" method="POST">
    {% csrf_token %}
    
    <div class="form-group">
        <label class="control-label col-sm-2" for="username"><strong>Username:</strong></label>
        <br><br>
        <div class="col-sm-10">
     <input type="text" class="form-control" name="username" placeholder="Enter username" >
        </div>
    </div>
  
    <div class="form-group">
       <label class="control-label col-sm-2"  for="password"><strong>Password:</strong></label>
       <br><br>
     <div class="col-sm-10">
       <input class="form-control" type="password" name="password" placeholder="Enter Password">
   </div>
    </div>
    <div class="form-group">        
        <div class="col-sm-offset-2 col-sm-10">
                <div class="checkbox">
                        <label><input type="checkbox" name="remember"><strong style="color:aliceblue">Remember me</strong></label>
                    </div>
                  </div>
                </div>
     <div class="form-group">       
        <div class="col-sm-offset-2 col-sm-10">
     <input type="submit" name=""   class="btn btn-default" value="Login">
        </div>
     </div>
    </div>
    </form>
      </div>
        </div>
        </div>
{% endblock %}
      </body>   

codefundo/templates/codefundo/afterlogsign.html
{% block main_content %}
{% load staticfiles %}   
<!DOCTYPE html>
<html lang="en">
 
<body style="background-image:url({% static 'codefundo/water1.jpg' %}); background-repeat: no-repeat">
      
    <head>
            <style>
            ul {
                list-style-type: none;
                margin: 0;
                padding: 0;
                overflow: hidden;
                background-color: #333;
            }
            
            li {
                float: left;
            }
            
            li a {
                display: block;
                color: white;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
            }
            
            li a:hover {
                background-color: #111;
            }
            .fund
{
	position: absolute;
	top: 50%;
	left: 50%;
	transform: translate(-50%,-50%);
	width: 400px;
	height: 600px;
	padding: 50px 40px;
	box-sizing: border-box;
	background: rgba(0,0,0,.5);
}
            </style>
            </head>
            <body>
            
            <ul>
              <li><a class="active" href="/codefundo/main_page">Home</a></li>
              <li><a href="#news"></a></li>
              <li><a href="/codefundo/admin_login">Admin Portal</a></li>
              <li><a href="/codefundo/aboutus">About Us</a></li>
              <li><a href="/codefundo/main_page">Log Out</a></li>
            </ul>
            
        

<div class="container">
    <div class="fund">
            <form  action="/codefundo/afterlogsign/" method="POST">
          
                {% csrf_token %}
       {{ form.non_field_errors }}


       <h1 style=" text-align: center"><strong style="color:aliceblue">Submit Your Contributions Here</strong> </h1><br>

           <strong>Funds :</strong> <br> {{form.fund}}<br><br>


<form class="form-horizontal" action="{% url "codefundo:user_login" %}" method="POST">
    {% csrf_token %}
    
    <div class="form-group">
        <label class="control-label col-sm-2" for="card number"><strong>Enter Atm Card Number:</strong></label>
        <br>
        <div class="col-sm-10">
     <input type="text" class="form-control" name="card" placeholder="Enter Card Number" >
        </div>
    </div>
  <br>
    <div class="form-group">
       <label class="control-label col-sm-2"  for="card name"><strong>Enter Card Holder Name:</strong></label>
       <br>
     <div class="col-sm-10">
       <input class="form-control" type="text" name="name" placeholder="Enter Name">
   </div>
    </div>
<br>
    <div class="form-group">
            <label class="control-label col-sm-2"  for="cvv"><strong>Enter CVV:</strong></label>
            <br>
          <div class="col-sm-10">
            <input class="form-control" type="password" name="cvv" placeholder="Enter CVV">
        </div>
         </div>
<br>
         <div class="form-group">
                <label class="control-label col-sm-2"  for="date"><strong>Enter Date of Expiry:</strong></label>
                <br>
              <div class="col-sm-10">
                <input class="form-control" type="text" name="date" placeholder="MM/YYYY">
            </div>
             </div>
           <br>
      
         total fund till now:{{sum}}
        

<br>
                <input class="btn btn-success" type="submit" value="submit">   
            </form>   
 
    </div>
   
 
    </div>
</div>

</body>
</html>
   {% endblock %}

codefundo/templates/codefundo/alreadyreg.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Microsoft Codefundoo</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
    body{
background-image:url({% static 'codefundo/rain2.jpg' %});
background-repeat:no-repeat;
background-size:100%;
}
    /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
    .row.content {height: 1500px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      background-color: #f1f1f1;
      height: 100%;
    }
    
    .circle
  {
    border-radius: 50%;
    width: 200px;
    height: 200px; 
    background-color: rgb(45, 218, 45)
  }

  .circle1{
    border-radius: 50%;
    width: 200px;
    height: 200px; 
    background-color: rgb(103, 155, 103)
  }
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }

    .col-sm-9{
      background-image: :url({% static 'codefundo/rain.jpg' %});
      background-repeat: no-repeat;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height: auto;} 
    }
  </style>
</head>
<body>

<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <h4>MICROSOFT</h4>
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="/codefundo/main_page/">Home</a></li>
        <li><a href="/codefundo/aboutus/">About Us</a></li>
        <li><a href="/codefundo/user_signup/">Sign Up</a></li>
        <li><a href="/codefundo/user_login">Log In</a></li>
      </ul><br>

      <div class="container">
        <form  action="/codefundo/main_page/" method="POST">
      
            {% csrf_token %}
   {{ form.non_field_errors }}

        
       <label for="Aadhar">Aadhar Card:</label>
         <br> {{form.aadhar_no}}<br><br>
       
  
         <label for="pin">Postal Code</label>
        <br> {{form.pincode}}
        <br><br>

        <label for="City">City</label>
        <br>  {{form.city}}
        <br>
            <strong>You have already Registered!</strong>
<br>
<br>
            <input class="btn btn-primary" type="submit" value="Submit Response">   
        </form>  
<br>
<br> 


</div>

</div>

    <div class="col-sm-9">
        
        <br>
      <h2>MICROSOFT: Always Happy To Help</h2>
      <h5><span class="glyphicon glyphicon-time"></span> About us</h5>
      <br>
      <p>This website is concerned with the number of people around a particular place... So that we can reach them and help them from Natural Calamity </p>
      <br><br>

      

      <div class="animated zoomIn">
      <div class="row">
          {% for j in objects %}
          <div class="col-sm-4">
            <div class="circle">
              <div style="text-align: center">
                <br>
                <br>
            <strong>Pincode</strong>   <div>{{j.pincode}}</div>
              <strong>Number of People</strong> <div>{{j.user_count}}</div>
          <strong>Funds alloted</strong>     <div>{{j.fund}}</div>
               <br>
               <br>
              </div>
  
            </div>
            <br>
          </div>
    
    {% endfor %}
        
  </div>

</div>


<footer class="container-fluid">
  <p>Contact Us</p>
  <p>mananpoddarm@gmail.com</p>
  <p>17shashank17@gmail.com</p>
</footer>
</body>
</html>

codefundo/templates/codefundo/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    
    
<title>share_nitk</title>


<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="mystyle.css">
<link rel="stylesheet" type="text/css" href="content.css">



<link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">
<link href='https://fonts.googleapis.com/css?family=Amethysta' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Bitter' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Barlow' rel='stylesheet'>
<link rel="stylesheet" type="text/css" href="{% static "pastebin/prism.css" %}">
<link href='https://fonts.googleapis.com/css?family=Amethysta' rel='stylesheet'>





<style>
    .parallax1 {
    /* The image used */
   
    background-image: url("{% static "blog/nitk.png" %}");

    /* Set a specific height */
    height: 30em; 

    /* Create the parallax scrolling effect */
    background-attachment: fixed;
    background-position: center;
    background-repeat: no-repeat;
    background-size:150em ;
    width: 100%;
}

.signup{
    margin-left: 25em;
    
   
}
.image{
    background-image: url("{% static "pastebin/nitk.png" %}");
    background-repeat:repeat-y;
    width:100%;
    margin:0; 
    padding:0; 
    height:100%;
    
}
.font_cool {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Raleway', sans-serif;
                font-weight: 100;
                height: 10em;
                margin: 0;
                text-align: center;
                margin-top:2em;
                font-size: 2.5em;
            }

.button {
    -webkit-transition-duration: 0.4s; /* Safari */
    transition-duration: 0.4s;
}

.button:hover {
    background-color: #4CAF50; /* Green */
    color: white;
}







</style>
</head>
               

<body>


        <div class="font_cool">
                <br><div class="hello">microsoft codefundo</div>
                
          
    
       
            {% block main_content %}
    {% endblock %}

</body>
</html>

codefundo/templates/codefundo/return_invalid_user.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<div class="container">
    <div style="text-align: center">
       <h1 style="margin-top: 4em;"> invalid username and password !<h1>

        <a href="{% url "codefundo:user_login" %}" class="btn btn-primary">login again</a>
        </h1>
       </h1>
    </div>

codefundo/templates/codefundo/return_valid_data.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<div class="container">
    <div style="text-align: center">
       <h1 style="margin-top: 4em;"> seems like you didn't enter some mandatory fields ! please enter valid data   !<h1>

        <a href="{% url "codefundo:main_log_page" %}" class="btn btn-primary">go to main page</a>
        </h1>
       </h1>
    </div>