blog/urls.py
from django.conf.urls import url
from blog import views
app_name = "blog"

urlpatterns = [
    url(r'^formpage/', views.form_name_view, name='form_name'),
    url(r'^signup/', views.authentication_view, name='authentication_name'),
    url(r'^main_page/', views.main_page, name='main_page'),
    url(r'^logout/', views.user_logout, name='user_logout'),
    
    
    url(r'^user_login/', views.user_login, name='user_login'),
   
   
]

mysite/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path



urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^polls/', include("blog.urls" , namespace="polls")),#manageNitkroute
    url(r'^pastebin/', include("pastebin.urls" , namespace="pastebin")),#pastebin
    url(r'^tinymce/', include('tinymce.urls')),#pastebin
    url(r'^codefundo/', include("codefundo.urls" , namespace="codefundo")),#codefundo
    


]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pastebin/urls.py
from django.conf.urls import url
from pastebin import views
app_name = "pastebin"

urlpatterns = [
    url(r'^$', views.front_page, name='front_page'),

    url(r'^main_page/', views.main_page, name='main_page'),
    url(r'^(?P<url_no>[0-9]+)/$', views.content_fetch, name='content'),
    url(r'^logged_in/(?P<url_no>[0-9]+)/$', views.content_fetch_logged_in, name='content_logged_in'),

    url(r'^user_login/', views.user_login, name='user_login'),
    url(r'^user_signup/', views.user_signup, name='user_signup'),
    url(r'^main_loggedin_page/', views.main_loggedin_page, name='main_loggedin_page'),
    url(r'^user_logout/', views.user_logout, name='user_logout'),
    url(r'^(?P<pk>[0-9]+)/edit/', views.paste_edit, name='paste_edit'),
    url(r'^(?P<pk>[0-9]+)/edit_logged_in/', views.paste_edit_logged_in, name='paste_edit_logged_in'),







   
   
   
]

pastebin/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User
from tinymce.models import HTMLField
from ckeditor.fields import RichTextField
from datetime import timezone



class paste(models.Model):
    content = RichTextField(max_length=1000000)
    url = models.AutoField(primary_key=True)
    expiration_date= models.DateField(blank=True, null=True)
    editable = models.BooleanField(default=False)
class paste_logged_in(models.Model):
    content = models.TextField(max_length=1000000)
    url = models.AutoField(primary_key=True)
    owner=models.CharField(blank=True,max_length=60)
    expiration_date= models.DateField(blank=True, null=True)
    editable = models.BooleanField(default=False)

pastebin/forms.py
from django import forms
from django.core import validators
from pastebin.models import paste,User,paste_logged_in
from django.db import models



class input(forms.ModelForm):
    url = models.AutoField(primary_key=True)
    class Meta:
        model = paste
        fields= '__all__'

class input_logged_in(forms.ModelForm):
    url = models.AutoField(primary_key=True)
    class Meta:
        model = paste_logged_in
        fields= '__all__'


class Authentic(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields =("username","password","first_name","last_name","email",)

pastebin/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
import datetime
from django import template
from django.utils import timezone

from django.shortcuts import render,get_object_or_404
from pastebin.forms import input,Authentic,input_logged_in
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from pastebin.models import paste,paste_logged_in
from datetime import datetime,date,timedelta
from django.views.generic.edit import CreateView, UpdateView, DeleteView



def front_page(request):
 return render(request,"pastebin/front_page.html") 



def main_page(request):
    form=input()
    mypaste=paste.objects.all()
    mypaste = sorted(mypaste,key=lambda x:x.url,reverse=True)

    if request.method=="POST":
        form=input(request.POST)
        mydate=request.POST.get("date",)
        ins = form.save(commit=False)
        ins.expiration_date=mydate
        year,month,day=map(int,mydate.split("-"))
        mydate=date(year,month,day)
        diff=mydate-date.today()
        if diff.days<0:
            return render(request,"pastebin/return_invalid_date.html")
        else:
        #date_i=date.today()-mydate
         if form.is_valid():
            latest_model=form.save()
            var3=latest_model.url
            return render(request,"pastebin/ss.html",{"form":form,"var3":var3, }) 
         else:
               return render(request,"pastebin/return_valid_data.html")   
    return render(request,"pastebin/paste.html",{"form":form ,"mypaste":mypaste[:10]}) 
@login_required
def main_loggedin_page(request):
   form=input_logged_in()

   usernam=request.user.username
   var=form.save(commit=False)
   var.owner=usernam
   print(usernam)
   mypaste=paste_logged_in.objects.filter(owner=usernam)
   mypaste = sorted(mypaste,key=lambda x:x.url,reverse=True)
   #mypaste=paste_logged_in.objects.all() 
   if request.method=="POST":
        form=input_logged_in(request.POST)
        mydate=request.POST.get("date",)

        var=form.save(commit=False)
        var.expiration_date=mydate
        year,month,day=map(int,mydate.split("-"))
        mydate=date(year,month,day)
        diff=mydate-date.today()
        var.owner=usernam
        if diff.days<0:
            return render(request,"pastebin/return_invalid_date_log.html")
        else:
         if form.is_valid():
            latest_model=form.save()
            var3=latest_model.url
            return render(request,"pastebin/ss_logged_in.html",{"form":form,"var3":var3,"username":usernam}) 
         else:
               return render(request,"pastebin/return_valid_datalog.html")

   return render(request,"pastebin/paste_loggedin.html",{"form":form,"username":usernam ,"mypaste":mypaste[:50],}) 



def content_fetch(request,url_no):
     content_object=paste.objects.get(pk = url_no)
     mydate = content_object.expiration_date
     
     diff=mydate-date.today()
     print(diff.days)
     if diff.days<0:
            return render(request,"pastebin/return_link_expired.html")
     else:
         return render(request,"pastebin/fetching_content.html",{"content_object":content_object,"var3":url_no ,"days":diff.days})

def content_fetch_logged_in(request,url_no):
    content_object=paste_logged_in.objects.get(pk = url_no)
    mydate = content_object.expiration_date
    diff=mydate-date.today()
    usernam=request.user.username
    if diff.days<0:
            return render(request,"pastebin/return_link_expired.html")
    else:
        return render(request,"pastebin/fetching_content_logged_in.html",{"content_object":content_object ,"var3":url_no,"username":usernam ,"days":diff.days}) 


def user_signup(request):
    registered = False
    
    if request.method=="POST":
     auth=Authentic(request.POST )

     if auth.is_valid():
         auth=auth.save(commit=False)
         auth.set_password(auth.password)   
         #hashing the password
         auth.save()
         registered=True


     else :
         print("error")
    else:
        auth=Authentic()     
    return render(request,"pastebin/signup.html",{"auth":auth,"registered":registered })        


def user_login(request):
    if request.method=="POST":
        username=request.POST.get("username")
        password=request.POST.get("password")

        user=authenticate(username=username,password=password)


        if user:
            login(request,user)
            return HttpResponseRedirect(reverse("pastebin:main_loggedin_page",))
        else:
            return render(request,"pastebin/return_invalid_user.html")
    else :
        return render(request,"pastebin/login.html",{})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("pastebin:main_page",))


def paste_edit(request,pk):
    my_record = paste.objects.get(url=pk)
    if my_record.editable==False :
        return render(request,"pastebin/return_edit_excess.html")
    else:
     form = input(instance=my_record)
    
     if request.method=="POST":
        form = input(request.POST, instance=my_record)
        form.save()
        return render(request,"pastebin/return_edit.html")
     return render(request,"pastebin/paste_edit.html",{"form":form,"pk":pk})

def paste_edit_logged_in(request,pk):
    my_record = paste_logged_in.objects.get(url=pk)
    if my_record.editable==False:
        return render(request,"pastebin/return_edit_excesslog.html")
    else:

     form = input_logged_in(instance=my_record)
     if request.method=="POST":
        form = input_logged_in(request.POST, instance=my_record)
        form.save()
        return render(request,"pastebin/return_edit_log.html")
     return render(request,"pastebin/paste_edit_logged_in.html",{"form":form,"pk":pk}) 

pastebin/templates/pastebin/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    
    
<title>share_nitk</title>


<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="mystyle.css">
<link rel="stylesheet" type="text/css" href="content.css">



<link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">
<link href='https://fonts.googleapis.com/css?family=Amethysta' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Bitter' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Barlow' rel='stylesheet'>
<link rel="stylesheet" type="text/css" href="{% static "pastebin/prism.css" %}">
<link href='https://fonts.googleapis.com/css?family=Amethysta' rel='stylesheet'>





<style>
    .parallax1 {
    /* The image used */
   
    background-image: url("{% static "blog/nitk.png" %}");

    /* Set a specific height */
    height: 30em; 

    /* Create the parallax scrolling effect */
    background-attachment: fixed;
    background-position: center;
    background-repeat: no-repeat;
    background-size:150em ;
    width: 100%;
}

.signup{
    margin-left: 25em;
    
   
}
.image{
    background-image: url("{% static "pastebin/nitk.png" %}");
    background-repeat:repeat-y;
    width:100%;
    margin:0; 
    padding:0; 
    height:100%;
    
}
.font_cool {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Raleway', sans-serif;
                font-weight: 100;
                height: 10em;
                margin: 0;
                text-align: center;
                margin-top:2em;
                font-size: 2.5em;
            }









</style>
</head>

<script>
    
        document.getElementById("demo").innerHTML="This Web a
    function callabout(){pplication is developed for a project of web enthusiast club by me."+
        "you can visit me on my personal website on mananpoddar.github.io"
    }

      function callcontact(){
                          document.getElementById("demo").innerHTML="<ul><li>&#35; 20,Block 7,NITK,  SURATHKAL</li><li>INDIA</li><li>+91&nbsp;9113536695</li><li><a href=mailto:mananpoddarm@gmail.com style=text-decoration:none>&#9993;"+
                         " mananpoddarm@gmail.com</a></li></ul>"
                  }

                </script>                 
 <!-- <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
  <script>tinymce.init({ selector:'textarea' });</script>
  <script src="{% static 'pastebin/js/tinymce/tinymce.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'pastebin/js/tinymce/custom.js' %}" ></script>-->

                  

<body>


        <div class="font_cool">
                <br><div class="hello">We nitikians are proud to have our personal hub for sharing codes</div><br><br>
                
          
    
       
            {% block main_content %}
    {% endblock %}
<!--
          <nav class="navbar navbar-default" >
                <div class="container">
                <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>                        
                              </button>
                    <a href="#!" onclick="callabout()"class="navbar-brand">About</a>  
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav">
           
                 <li>  <a href="#!" onclick="callcontact()">Contact Me</a></li>
                 </ul> 
                </div>
        </nav>
        <div class="container">
                <div class="main_content" style="font-family:Amethysta">
                   <div   id="demo">
                      <div  >This website provides us to share our code easily </div>
                       </div>
                    </div>
                  </div>
              </div>
   


</div>
-->
</body>
</html>

pastebin/templates/pastebin/fetching_content.html
{% load staticfiles %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<link rel="stylesheet" type="text/css" href="{% static "/pastebin/prism.css" %}">
 <script src="{% static "pastebin/prism.js" %}"></script>
<br><br><br><br>

<nav class="navbar navbar-default" >
                <div class="container">
                <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>                        
                              </button>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav">
                    <li>  <a href="#!" class="active">welcome {{username}}</a>    </li>
                 <li>  <a href="/pastebin/{{var3}}/edit/">edit here</a></li>


                 
                 </ul> 
                </div>
        </nav>


 <div style="margin-left: 100em;">
   
        <i class="fa fa-share-alt" style="font-size:36px"></i>
        </div>
<div style="margin-left: 100em;">
<!-- AddToAny BEGIN -->

<div class="a2a_kit a2a_kit_size_32 a2a_default_style">
                <a class="a2a_dd" href="https://www.addtoany.com/share"></a>
                <a class="a2a_button_facebook"></a>
                <a class="a2a_button_twitter"></a>
                <a class="a2a_button_google_plus"></a>
                </div>
                <script async src="https://static.addtoany.com/menu/page.js"></script>
                <!-- AddToAny END -->
        </div>
</div>


<div class="container">
  
    <div style="text-align: center"><br>
        <a href="{% url "pastebin:main_page" %}" class="btn btn-primary">go to main page</a>
<br>
       <h1 > code you are looking for is here!<h1>
  <div style="text-align:left ; "><pre> <code class="language-javascript"> <pre>  {{content_object.content|safe }} </pre></code></pre></div><br>
<div  style="font-size: 1.5em;">the content will expire in {{days}} day/s</div>

</div>

pastebin/templates/pastebin/fetching_content_logged_in.html
{% extends "pastebin/base.html" %}
{% block main_content %}
{% load staticfiles %}
<nav class="navbar navbar-default" >
                <div class="container">
                <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>                        
                              </button>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav">
                    <li>  <a href="#!" class="active">welcome {{username}}</a>    </li>
                 <li>  <a href="/pastebin/{{var3}}/edit_logged_in/">edit here</a></li>
                 <li>  <a href="{% url "pastebin:user_logout" %}" class="active">logout</a>    </li>


                 
                 </ul> 
                </div>
        </nav>

        <link rel="stylesheet" type="text/css" href="{% static "pastebin/prism.css" %}">
        <script src="{% static "pastebin/prism.js" %}"></script>
        <div style="margin-left: 35em;">
        <i class="fa fa-share-alt" style="font-size:36px"></i>
        </div>
<div style="margin-left: 45em;">
<!-- AddToAny BEGIN -->

<div class="a2a_kit a2a_kit_size_32 a2a_default_style">
                <a class="a2a_dd" href="https://www.addtoany.com/share"></a>
                <a class="a2a_button_facebook"></a>
                <a class="a2a_button_twitter"></a>
                <a class="a2a_button_google_plus"></a>
                </div>
                <script async src="https://static.addtoany.com/menu/page.js"></script>
                <!-- AddToAny END -->
        </div>
</div>
<div class="container">
    <div style="text-align: center">
       <h1 style="margin-top: .5em;"> code you are looking for is here!<h1>
            
        <div style="text-align:left ; "><pre> <code class="language-javascript"> <pre> {{content_object.content|safe}}</pre></code></pre></div>
</div><br> 


</div>
<div class="container"> 


<a href="{% url "pastebin:main_loggedin_page" %}" class="btn btn-primary">go to main page</a>
<br><br><br>
<div  style="font-size: 3em;">the content will expire in {{days}} day/s</div>

{% endblock %}

pastebin/templates/pastebin/input_update.html
{% extends "pastebin/base.html" %}
{% block main_content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>
{% endblock %}

pastebin/templates/pastebin/paste.html
{% extends "pastebin/base.html" %}
{% block main_content %}
{% load staticfiles %}    <body>

 <!--navbar-->
 <link rel="stylesheet" type="text/css" href="{% static "/pastebin/prism.css" %}">
 <script src="{% static "pastebin/prism.js" %}"></script>
 {% load static %}
 <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
 <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
         
 <nav class="navbar navbar-default" >
        <div class="container">
        <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>                        
                      </button>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
         <li>  <a href="{% url "pastebin:user_login" %}" class="active">login</a>    </li>
         <li>   <a href="{% url "pastebin:user_signup" %}" class="dropdown" >signup</a></li>
        
         </ul> 
        </div>
</nav>


       
<script>
    webshim.setOptions('forms-ext', {
replaceUI: 'auto',
types: 'date',
date: {
    startView: 2,
    inlinePicker: true,
    classes: 'hide-inputbtns'
}
});
webshim.setOptions('forms', {
lazyCustomMessages: true
});
//start polyfilling
webshim.polyfill('forms forms-ext');

//only last example using format display
$(function () {
$('.format-date').each(function () {
    var $display = $('.date-display', this);
    $(this).on('change', function (e) {
        //webshim.format will automatically format date to according to webshim.activeLang or the browsers locale
        var localizedDate = webshim.format.date($.prop(e.target, 'value'));
        $display.html(localizedDate);
    });
});
});
</script>



<div class="container">

<div style="background-color: black">
<span>share your code with us</span>

<pre><code class="language-javascript">
        var myObject = {
        property1: "something",
        property2: 5,
        property3: true
        }; 
        </code></pre>

</div></div>    <br><br>

<div class="row">
    <div class="col-sm-8">
            <form class="form-horizontal" action="/pastebin/main_page/" method="POST">
          
                {% csrf_token %}
       {{ form.non_field_errors }}


<br>


        <div class="container" style="margin-right: 3em;font-family:Amethysta"  >
            your code/text: </div><br> {{form.media}}{{form.content }}<br><br>
           
      
            <div class="container"  style="font-family:Amethysta">expiration date</div><div style="font-size: .5em;font-family:Amethysta">this field is mandatory</div>
            <div class="form-row">
                <input type="date" class="hide-replaced" name="date" />
            </div>
            <br>
           <div>edit access</div>
           {{form.editable}}
<br>

                <input class="btn btn-primary" type="submit" value="upload">   
            </form>   
 
    </div>
    <br>
    <div class="col-sm-4"><div class="container-fluid" style="font-family:Amethysta">see what is trending here within coders of nitk by viewing recent 10 shares !</div>
    <br>
          {% for items in mypaste %} 
         <a href="/pastebin/{{items.url}}"> pastebin/{{items.url}}</a> <br>
          
          {% endfor %}</div>
</div>
 
    </div>


   {% endblock %}

pastebin/templates/pastebin/paste_edit_logged_in.html
{% extends "pastebin/base.html" %}
{% block main_content %}
    <body>



        <nav class="navbar navbar-default" >
                <div class="container">
                <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>                        
                              </button>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav">
                 <li>  <a href="#!" class="active">welcome {{username}}</a>    </li>

 
                
                 </ul> 
                </div>
        </nav>
<div class="container">now edit your codes without changing the link ! </div>

            <form class="form-horizontal" action="/pastebin/{{pk}}/edit_logged_in/" method="POST">
                {% csrf_token %}
       {{ form.non_field_errors }}
        <div class="container" style="font-family: cursive">
            your text/code:<br>{{form.content }}<br>
            <div>expiration_date</div>
            {{form.expiration_date}}   
            <div>owner of the code ( don't change it ).</div>
            {{form.owner}}   
      <br>
                <input class="btn btn-primary" type="submit" value="Submit">   
            </form>   
  </div>
     <div class="col-sm-4">
     </div>
  </div>
</div>



  {% endblock %}

pastebin/templates/pastebin/paste_loggedin.html
{% extends "pastebin/base.html" %}
{% block main_content %}
{% load staticfiles %}
    <body>
            <link rel="stylesheet" type="text/css" href="{% static "/pastebin/prism.css" %}">
            <script src="{% static "pastebin/prism.js" %}"></script>
            {% load static %}
            <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
            <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

        <nav class="navbar navbar-default" >
                <div class="container">
                <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>                        
                              </button>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav">
                 <li>  <a href="#!" class="active">welcome {{username}}</a>    </li>
                    <li>  <a href="{% url "pastebin:user_logout" %}" class="active">logout</a>    </li>

 
                
                 </ul> 
                </div>
        </nav>


        <script>
            webshim.setOptions('forms-ext', {
        replaceUI: 'auto',
        types: 'date',
        date: {
            startView: 2,
            inlinePicker: true,
            classes: 'hide-inputbtns'
        }
        });
        webshim.setOptions('forms', {
        lazyCustomMessages: true
        });
        //start polyfilling
        webshim.polyfill('forms forms-ext');
        
        //only last example using format display
        $(function () {
        $('.format-date').each(function () {
            var $display = $('.date-display', this);
            $(this).on('change', function (e) {
                //webshim.format will automatically format date to according to webshim.activeLang or the browsers locale
                var localizedDate = webshim.format.date($.prop(e.target, 'value'));
                $display.html(localizedDate);
            });
        });
        });
        </script>


        <div class="container-fluid">


<div class="row">
  <div class="col-sm-8">
            <form class="form-horizontal" action="/pastebin/main_loggedin_page/" method="POST">
                {% csrf_token %}
       {{ form.non_field_errors }}
          <div style="font-family:Amethysta">  your text:<br>{{form.media}}{{form.content }}<br><br></div>
            <url:>
             <em>&nbsp;</em><br><br>
      <div class="container"  style="font-family:Amethysta">expiration date</div><div style="font-size: .5em;font-family:Amethysta">this field is mandatory</div>

             <div class="form-row">
                <input type="date" class="hide-replaced" name="date" />
            </div>
            <br>
            <div>edit access</div>
            {{form.editable}}
 <br>
                <input class="btn btn-primary" type="submit" value="Submit it">   
            </form>   
</div>
     <div class="col-sm-4"><div class="container-fluid" style="font-family:Amethysta">all the tough task of managing your shared codes is on us !</div>
              <br>

              {% if mypaste %}
                    {% for items in mypaste %} 
                   <a href="/pastebin/logged_in/{{items.url}}"> pastebin/logged_in/{{items.url}}</a> <br>
                    
                    {% endfor %}</div>
</div>{% else %}
<div>paste history is empty right now ! share your code with us we will take care of your links here
</div>
{% endif %}


{% endblock %}
   

pastebin/templates/pastebin/return_edit_log.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<div class="container">
    <div style="text-align: center">
       <h1 style="margin-top: 4em;"> SUCCESSFULLY EDITED !<h1>

        <a href="{% url "pastebin:main_loggedin_page" %}" class="btn btn-primary">go to main page</a>
        </h1>
       </h1>
    </div>

pastebin/templates/pastebin/ss_logged_in.html
{% extends "pastebin/base.html" %}
{% block main_content %}

<nav class="navbar navbar-default" >
                <div class="container">
                <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>                        
                              </button>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav">
                 <li>  <a href="#!" class="active">welcome {{username}}</a>    </li>
                 <li>  <a href="/pastebin/{{var3}}/edit_logged_in/">edit here</a></li>
                 <li>  <a href="{% url "pastebin:user_logout" %}" class="active">logout</a>    </li>


                 
                 </ul> 
                </div>
        </nav>


<div class="container">
    <div style="text-align: center">
       <h1 style="margin-top: 4em;"> SUCCESSFULLY SUBMITTED!</h1></div>
</div>
            <a href="/pastebin/logged_in/{{var3}}" style="font-size: 1em   ; text-decoration: none;text-align: left">http://mananm.pythonanywhere.com/pastebin/logged_in/{{var3}}</a>
            {{var.content}}<br><br><br>
            {{var1}}  <br>{{latest_model1}}<br>{{var.owner}}

           

            <a href="{% url "pastebin:main_loggedin_page" %}" class="btn btn-primary">go to main page</a>
<br>
        </div>

</div>


{% endblock %}